# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'weibo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weibo

pod 'AFNetworking', '~> 3.1.0'

end
